# Generated by Django 4.0.4 on 2022-04-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20190410_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
