# Generated by Django 4.0.4 on 2022-04-25 17:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_alter_employee_sex_alter_employee_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='region',
        ),
        migrations.AlterField(
            model_name='emergency',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+919009009082', help_text='Enter number with Country Code Eg. +919009009082', max_length=128, region=None, verbose_name='Phone Number (Example +919009009082)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('Senior High', 'Senior Secondary School'), ('Junior High', 'Higher Secondary School'), ('Primary Level', 'Primary School'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], default='Senior High', help_text='highest educational standard ie. your last level of schooling', max_length=20, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Intern', 'Intern')], default='Full-Time', max_length=15, null=True, verbose_name='Employee Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=25, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+919009009082', help_text='Enter number with Country Code Eg. +919009009082', max_length=128, region=None, verbose_name='Phone Number (Example +919009009082)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss')], default='Mr', max_length=25, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number of Next of Kin', max_length=128, null=True, region=None, verbose_name='Next of Kin Phone Number (Example +919009009082)'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Enter number with Country Code Eg. +919009009082', max_length=128, null=True, region=None, verbose_name='Spouse Phone Number (Example +919009009082)'),
        ),
    ]
